// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2uo_yCEbqoz6s2gm5u8p1K0KpJredHc',
    appId: '1:935085747912:android:d5e6f06537531c2f48bffd',
    messagingSenderId: '935085747912',
    projectId: 'dude-classdev',
    storageBucket: 'dude-classdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWCO2UDLdly5bI4pOnXpvPx97ZgHwGoJQ',
    appId: '1:935085747912:ios:20fc872922f4df9748bffd',
    messagingSenderId: '935085747912',
    projectId: 'dude-classdev',
    storageBucket: 'dude-classdev.appspot.com',
    androidClientId: '935085747912-242gukgra6u2l72k521mh7vuon8k6bsn.apps.googleusercontent.com',
    iosClientId: '935085747912-7eqaff1hnimda2kafpe2l7f3h4g7jflk.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCalling',
  );
}
